/**
 * Xcode 27 refuses to build a pod whose own iOS deployment target is below
 * 15.0 — it's an error now, not a warning. Two dependencies still declare
 * older ones (async-storage's resource bundle at 13.4, react-native-svg's
 * filters at 12.4), so after `pod install` this raises every pod target that
 * sits below the app's minimum up to it.
 *
 * It lives here rather than as an edit to ios/Podfile because ios/ is
 * generated by `expo prebuild` / `expo run:ios` and isn't committed: an edit
 * there would vanish the next time the folder is regenerated.
 */
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const MARK = '# nura: raise pod deployment targets';

module.exports = function withPodsDeploymentTarget(config, { min = '15.1' } = {}) {
  return withDangerousMod(config, ['ios', async (cfg) => {
    const file = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
    let src = fs.readFileSync(file, 'utf8');
    if (src.includes(MARK)) return cfg;

    const hook = [
      `    ${MARK}`,
      `    installer.pods_project.targets.each do |t|`,
      `      t.build_configurations.each do |c|`,
      `        current = c.build_settings['IPHONEOS_DEPLOYMENT_TARGET']`,
      `        if current.nil? || Gem::Version.new(current) < Gem::Version.new('${min}')`,
      `          c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${min}'`,
      `        end`,
      `      end`,
      `    end`,
      '',
    ].join('\n');

    // after react_native_post_install(...), so nothing it does can undo this
    const rnHook = /(\n[ \t]*react_native_post_install\([\s\S]*?\n[ \t]*\)\n)/;
    if (!rnHook.test(src)) throw new Error('withPodsDeploymentTarget: react_native_post_install not found in Podfile');
    src = src.replace(rnHook, `$1${hook}`);
    fs.writeFileSync(file, src);
    return cfg;
  }]);
};
