/**
 * iOS 27 refuses to launch an app that hasn't adopted the scene-based life
 * cycle: UIKit traps at launch (_UIApplicationEvaluateRuntimeIssueFor-
 * NoSceneLifecycleAdoption). Expo 57 ships the piece that does the work —
 * ExpoAppSceneDelegate creates the window from the connecting scene, starts
 * React Native in it, and forwards URL, user-activity and life-cycle events
 * back to the app delegate — but the prebuild template still generates an
 * app-delegate-only app. This plugin switches it over:
 *
 *  - Info.plist declares one window scene, handled by EXExpoAppSceneDelegate.
 *  - AppDelegate conforms to ExpoReactNativeFactoryProvider and stops making
 *    its own window: it creates the factory, and the scene delegate starts
 *    React Native into the scene's window.
 *
 * A plugin rather than an edit to ios/, because ios/ is regenerated by
 * `expo prebuild` and isn't committed.
 */
const { withInfoPlist, withAppDelegate } = require('expo/config-plugins');

const START_BLOCK = /#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\([\s\S]*?\)\n#endif\n/;

module.exports = function withSceneLifecycle(config) {
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [{
          UISceneConfigurationName: 'Default Configuration',
          UISceneDelegateClassName: 'EXExpoAppSceneDelegate',
        }],
      },
    };
    return cfg;
  });

  config = withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error('withSceneLifecycle: expected a Swift AppDelegate');
    }
    let src = cfg.modResults.contents;
    if (src.includes('ExpoReactNativeFactoryProvider')) return cfg;   // already applied

    const decl = 'class AppDelegate: ExpoAppDelegate {';
    if (!src.includes(decl) || !START_BLOCK.test(src)) {
      throw new Error('withSceneLifecycle: AppDelegate template changed — update the plugin');
    }
    src = src.replace(decl, 'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {');
    src = src.replace(START_BLOCK,
      '    // No window here: iOS 27 requires the scene life cycle, so ExpoAppSceneDelegate\n' +
      '    // creates the window from the scene and starts React Native into it\n' +
      '    // (Info.plist → UIApplicationSceneManifest; plugins/withSceneLifecycle.js).\n');
    cfg.modResults.contents = src;
    return cfg;
  });

  return config;
};
