/**
 * Xcode 27 refuses to build a pod whose own iOS deployment target is below
 * 15.0 — it's an error now, not a warning. Two dependencies still declare
 * older ones (async-storage's resource bundle at 13.4, react-native-svg's
 * filters at 12.4), so after `pod install` this raises every pod target that
 * sits below the app's minimum up to it.
 *
 * It also silences compiler warnings inside the pods. Xcode 27 reports about
 * 650 of them, all in React Native, Expo modules and react-native-svg, none
 * in Nura's own code — they drowned out any warning that would matter. The
 * app target keeps the warnings from its own code; what third-party headers
 * report there is quieted too (see appHook below).
 *
 * It lives here rather than as an edit to ios/Podfile because ios/ is
 * generated by `expo prebuild` / `expo run:ios` and isn't committed: an edit
 * there would vanish the next time the folder is regenerated.
 */
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const MARK = '# nura: raise pod deployment targets';
const APP_MARK = '# nura: quiet third-party headers in the app target';

module.exports = function withPodsDeploymentTarget(config, { min = '15.1' } = {}) {
  return withDangerousMod(config, ['ios', async (cfg) => {
    const file = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
    let src = fs.readFileSync(file, 'utf8');
    const hasPods = src.includes(MARK), hasApp = src.includes(APP_MARK);
    if (hasPods && hasApp) return cfg;

    const hook = [
      `    ${MARK}`,
      `    installer.pods_project.targets.each do |t|`,
      `      t.build_configurations.each do |c|`,
      `        current = c.build_settings['IPHONEOS_DEPLOYMENT_TARGET']`,
      `        if current.nil? || Gem::Version.new(current) < Gem::Version.new('${min}')`,
      `          c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${min}'`,
      `        end`,
      `        c.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'`,
      `        c.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'`,
      // Swift pods still report the React headers they import, and libtool
      // reports every empty object file
      `        swift = c.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'`,
      `        c.build_settings['OTHER_SWIFT_FLAGS'] = "#{swift} -Xcc -w" unless swift.include?('-Xcc -w')`,
      `        c.build_settings['OTHER_LIBTOOLFLAGS'] = '$(inherited) -no_warning_for_no_symbols'`,
      `      end`,
      `    end`,
      '',
    ].join('\n');

    // The app target, and one pod script phase. About 60 warnings were still
    // left after the pods went quiet, none of them from Nura: the app's Swift
    // files (AppDelegate, ExpoModulesProvider) import Expo's and React
    // Native's Objective-C headers, and clang reports those headers' warnings
    // (missing nullability, the legacy architecture's deprecations) against
    // the app. `-Xcc -w` quiets clang for imported headers only — warnings
    // from the app's own Swift still show. Hermes' "replace Hermes" script
    // has no declared outputs, so Xcode warns it runs on every build; it has
    // to, so it's marked as such.
    const appHook = [
      `    ${APP_MARK}`,
      `    installer.aggregate_targets.each do |at|`,
      `      at.user_project.native_targets.each do |t|`,
      `        t.build_configurations.each do |c|`,
      `          swift = c.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'`,
      `          c.build_settings['OTHER_SWIFT_FLAGS'] = "#{swift} -Xcc -w" unless swift.include?('-Xcc -w')`,
      `        end`,
      `      end`,
      `      at.user_project.save`,
      `    end`,
      `    installer.pods_project.targets.each do |t|`,
      `      t.shell_script_build_phases.each do |ph|`,
      `        ph.always_out_of_date = '1' if ph.name.to_s.include?('Hermes')`,
      `      end`,
      `    end`,
      '',
    ].join('\n');

    // after react_native_post_install(...), so nothing it does can undo this
    const rnHook = /(\n[ \t]*react_native_post_install\([\s\S]*?\n[ \t]*\)\n)/;
    if (!rnHook.test(src)) throw new Error('withPodsDeploymentTarget: react_native_post_install not found in Podfile');
    src = src.replace(rnHook, `$1${hasPods ? '' : hook}${hasApp ? '' : appHook}`);
    fs.writeFileSync(file, src);
    return cfg;
  }]);
};
