/**
 * The app's own sentence parser, for the site's "try it" box:
 * src/assistant.ts (with src/activities.ts and src/labels.ts) compiled with
 * the project's TypeScript into one browser script, nura-site/assets/nura-parser.js,
 * which sets window.NuraParser = { parseTask, describe, labelById, factLine,
 * understand, stripFiller, splitItems, rankActions } (the planner, src/next.ts,
 * so the demo's "start with" is the app's own pick). Image requires
 * (the activity scenes) become empty placeholders; the parser only reads words.
 *
 *   node scripts/site-parser.cjs      # after changing how Nu reads a sentence
 */
const ts = require('typescript');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
// the words only: understand (and the coach's local read, which splits a
// run-on sentence and hears how you feel) come along; the account, the
// device's database and the model are left out (`req` gives them {})
const modules = {
  './labels': 'src/labels.ts', './activities': 'src/activities.ts', './assistant': 'src/assistant.ts', './priority': 'src/priority.ts',
  './coach': 'src/coach.ts', './understand': 'src/understand.ts', './next': 'src/next.ts',
};

const compiled = Object.entries(modules).map(([name, file]) => {
  const src = fs.readFileSync(path.join(root, file), 'utf8');
  const js = ts.transpileModule(src, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, removeComments: true },
  }).outputText;
  return `  ${JSON.stringify(name)}: function (module, exports, require) {\n${js}\n  },`;
});

const out = `/* Generated by scripts/site-parser.cjs from src/assistant.ts, src/understand.ts and src/next.ts. Do not edit. */
(function () {
  var defs = {
${compiled.join('\n')}
  };
  var cache = {};
  function req(name) {
    if (!defs[name]) return {};                       // an image or a type-only module
    if (cache[name]) return cache[name].exports;
    var module = cache[name] = { exports: {} };
    defs[name](module, module.exports, req);
    return module.exports;
  }
  var a = req('./assistant'), l = req('./labels'), p = req('./priority'), u = req('./understand'), c = req('./coach'), n = req('./next');
  window.NuraParser = {
    parseTask: a.parseTask, describe: a.describe, labelById: l.labelById, factLine: p.factLine,
    understand: u.understandLocal, stripFiller: u.stripFiller, splitItems: c.splitItems,
    rankActions: n.rankActions,
  };
})();
`;
const dest = path.join(root, 'nura-site/assets/nura-parser.js');
fs.writeFileSync(dest, out);
console.log(`nura-parser.js: ${(fs.statSync(dest).size / 1024).toFixed(1)} KB`);
