/**
 * The app's own sentence parser, for the site's "try it" box:
 * src/assistant.ts (with src/activities.ts and src/labels.ts) compiled with
 * the project's TypeScript into one browser script, nura-site/assets/nura-parser.js,
 * which sets window.NuraParser = { parseTask, labelById, factLine }. Image requires
 * (the activity scenes) become empty placeholders; the parser only reads words.
 *
 *   node scripts/site-parser.cjs      # after changing how Nu reads a sentence
 */
const ts = require('typescript');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const modules = { './labels': 'src/labels.ts', './activities': 'src/activities.ts', './assistant': 'src/assistant.ts', './priority': 'src/priority.ts' };

const compiled = Object.entries(modules).map(([name, file]) => {
  const src = fs.readFileSync(path.join(root, file), 'utf8');
  const js = ts.transpileModule(src, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019, removeComments: true },
  }).outputText;
  return `  ${JSON.stringify(name)}: function (module, exports, require) {\n${js}\n  },`;
});

const out = `/* Generated by scripts/site-parser.cjs from src/assistant.ts. Do not edit. */
(function () {
  var defs = {
${compiled.join('\n')}
  };
  var cache = {};
  function req(name) {
    if (!defs[name]) return {};                       // an image or a type-only module
    if (cache[name]) return cache[name].exports;
    var module = cache[name] = { exports: {} };
    defs[name](module, module.exports, req);
    return module.exports;
  }
  var a = req('./assistant'), l = req('./labels'), p = req('./priority');
  window.NuraParser = { parseTask: a.parseTask, labelById: l.labelById, factLine: p.factLine };
})();
`;
const dest = path.join(root, 'nura-site/assets/nura-parser.js');
fs.writeFileSync(dest, out);
console.log(`nura-parser.js: ${(fs.statSync(dest).size / 1024).toFixed(1)} KB`);
